### ISSUE TITLE
Additional Headers Include

### ISSUE THREAD

**Issue by ibraheem15** [footedroom575/candr_cpp#1]
Is there any compatibility that I want to do g++ Hello.cpp pugixml.cpp -o abc?
If not please include this functionality as well

**Comment by footedroom575** [comment]
Hi @ibraheem15! I have now added support for compiling and running multiple files in [this commit](https://github.com/footedroom575/candr_cpp/tree/fd4099cb12d7ae26dddc0a81019811b2f0968b2a). Clone and install the script to update the previous one.

**Comment by footedroom575** [comment]
If you want to do `g++ Hello.cpp pugixml.cpp` and then later run 'em, just write:

`candr -m Hello pugixml`

**Comment by ibraheem15** [comment]
Ok Perfect Thanks
